{% set name = "galois" %}
{% set version = "0.4.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/galois-{{ version }}.tar.gz
  sha256: 94a371c995193a66798fceb079320dff154c21a0e3e0de388c06ba26f8eb574a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=62
    - wheel
    - setuptools-scm >=6.2
    - pip
  run:
    - python >={{ python_min }}
    - numpy >=1.21.0
    - numba >=0.55
    - typing_extensions >=4.0.0

test:
  imports:
    - galois
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: A performant NumPy extension for Galois fields and their applications
  description: |
    A performant NumPy extension for Galois fields and their applications.
  home: https://pypi.org/project/galois/
  dev_url: https://github.com/mhostetter/galois
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - project-alex22
    - mhostetter
